import argparse
import json
import os
import re
import subprocess
import time


def auto_select_cuda_device():
    visible = os.environ.get("CUDA_VISIBLE_DEVICES")
    if visible and visible.upper() != "ALL":
        return

    try:
        output = subprocess.check_output(
            [
                "nvidia-smi",
                "--query-gpu=index,memory.free",
                "--format=csv,noheader,nounits",
            ],
            text=True,
        )
    except Exception as exc:
        print(f"[Warning] Could not auto-select CUDA device: {exc}")
        return

    candidates = []
    for line in output.strip().splitlines():
        parts = [part.strip() for part in line.split(",")]
        if len(parts) != 2:
            continue
        try:
            candidates.append((int(parts[1]), parts[0]))
        except ValueError:
            continue
    if not candidates:
        return

    free_mb, gpu_index = max(candidates)
    os.environ["CUDA_VISIBLE_DEVICES"] = gpu_index
    print(f"Auto selected CUDA_VISIBLE_DEVICES={gpu_index} ({free_mb} MiB free)")


auto_select_cuda_device()

import cv2
from PIL import Image
from tqdm import tqdm
from ultralytics import YOLO
from vllm import LLM, SamplingParams

DEFAULT_DATASET_ROOT = "/mnt1/mnt2/data3/nlp/ws/course_data/dataset_divided_1"
DEFAULT_MODEL_PATH = "/mnt1/mnt2/data3/nlp/ws/model/Qwen3-VL-8B-Instruct"
DEFAULT_YOLO_PATH = "/mnt1/mnt2/data3/nlp/ws/model/YOLO26/yolo26m.pt"
DEFAULT_DATASET_FILE = os.path.join(DEFAULT_DATASET_ROOT, "train.jsonl")
DEFAULT_IMAGE_DIR = os.path.join(DEFAULT_DATASET_ROOT, "train_images")
DEFAULT_OUT_DIR = "/mnt1/mnt2/data3/nlp/ws/proj/课题组/results"

SYSTEM_PROMPT = (
    "You are an expert train driver and railway safety inspector utilizing an AI-assisted vision system. "
    "The image contains visual bounding boxes highlighting potential objects (trains, signals, obstacles) generated by the AI. "
    "Use these boxes as references, visually verify their accuracy, and answer the question following a strict 4-step cognitive process.\n\n"
    "Format your response EXACTLY as follows:\n"
    "Perception: Start with 'Visual analysis: ' and describe the environment, explicitly confirming or rejecting the provided bounding boxes.\n"
    "Reasoning: Start with 'Logical analysis: ' and analyze the situation based on safety protocols.\n"
    "Planning: Start with 'Action plan: ' and detail the necessary actions to ensure safety.\n"
    "Answer: Provide the final direct answer or correct option letter."
)

IMAGE_PLACEHOLDER = "<|vision_start|><|image_pad|><|vision_end|>"


def load_records(dataset_file):
    with open(dataset_file, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]


def build_question(data):
    raw_question = data["question"].strip()
    task_type = data.get("task_type", "qa")
    if task_type == "mc" and "options" in data:
        options = "\n\nOptions:"
        for key in sorted(data["options"].keys()):
            options += f"\n{key}: {data['options'][key]}"
        options += "\n\nFor the 'Answer' section, explicitly provide ONLY the correct option letter (e.g., A, B, C, or D)."
        return raw_question + options
    return raw_question


def build_prompt(question):
    return (
        f"<|im_start|>system\n{SYSTEM_PROMPT}<|im_end|>\n"
        f"<|im_start|>user\n{IMAGE_PLACEHOLDER}{question}<|im_end|>\n"
        "<|im_start|>assistant\n"
    )


def extract_answer(text, task_type):
    match = re.search(r"Answer:\s*(.*)", text, re.IGNORECASE | re.DOTALL)
    if match:
        ans = match.group(1).strip()
        if task_type == "mc":
            mc_match = re.search(r"([A-D])", ans, re.IGNORECASE)
            return mc_match.group(1).upper() if mc_match else ans
        return ans
    return text


def annotate_batch_with_yolo(yolo_model, images, batch_size):
    results = yolo_model(images, verbose=False, device=0, batch=batch_size)
    annotated_images = []
    for result in results:
        im_bgr = result.plot(line_width=2, font_size=10, labels=True)
        annotated_images.append(Image.fromarray(cv2.cvtColor(im_bgr, cv2.COLOR_BGR2RGB)))
    return annotated_images


def make_requests(records, image_dir, yolo_model, yolo_batch_size):
    images = [
        Image.open(os.path.join(image_dir, data["image_id"])).convert("RGB")
        for data in records
    ]
    images = annotate_batch_with_yolo(yolo_model, images, yolo_batch_size)
    requests = []
    meta = []
    for data, image in zip(records, images):
        task_type = data.get("task_type", "qa")
        requests.append({
            "prompt": build_prompt(build_question(data)),
            "multi_modal_data": {"image": image},
        })
        meta.append({
            "id": data["id"],
            "task_type": task_type,
            "answer": data["answer"],
        })
    return requests, meta


def iter_chunks(items, size):
    for start in range(0, len(items), size):
        yield start, items[start:start + size]


def load_existing_results(resume_path):
    if not resume_path or not os.path.exists(resume_path):
        return [], set()
    results = []
    seen_ids = set()
    with open(resume_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            item = json.loads(line)
            results.append(item)
            seen_ids.add(item["id"])
    return results, seen_ids


def append_jsonl(path, items):
    if not path or not items:
        return
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "a", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")
        f.flush()
        os.fsync(f.fileno())


def format_duration(seconds):
    seconds = int(max(seconds, 0))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours:d}h{minutes:02d}m{seconds:02d}s"
    if minutes:
        return f"{minutes:d}m{seconds:02d}s"
    return f"{seconds:d}s"


def main(args):
    records = load_records(args.dataset_file)
    os.makedirs(args.out_dir, exist_ok=True)
    resume_path = args.resume_file or os.path.join(args.out_dir, "ours_vllm_resume.jsonl")
    existing_outputs, seen_ids = load_existing_results(resume_path)
    records_to_run = [record for record in records if record["id"] not in seen_ids]
    if seen_ids:
        print(f"Resume enabled: loaded {len(seen_ids)} finished samples from {resume_path}")
    if not records_to_run:
        final_path = os.path.join(args.out_dir, f"proposed_vllm_results_{time.strftime('%y%m%d_%H%M')}.json")
        with open(final_path, "w", encoding="utf-8") as f:
            json.dump(existing_outputs, f, indent=4, ensure_ascii=False)
        print(f"All samples already finished. Results saved to {final_path}")
        return

    print(f"Visible CUDA devices: {os.environ.get('CUDA_VISIBLE_DEVICES', 'ALL')}")
    print(f"Loading YOLO model from {args.yolo_path}...")
    yolo_model = YOLO(args.yolo_path)
    yolo_model.to("cuda")

    print(f"Loading vLLM Qwen-VL from {args.model_path}...")
    llm = LLM(
        model=args.model_path,
        dtype="bfloat16",
        trust_remote_code=True,
        max_model_len=args.max_model_len,
        max_num_seqs=args.max_num_seqs,
        gpu_memory_utilization=args.gpu_memory_utilization,
        limit_mm_per_prompt={"image": 1},
        mm_processor_kwargs={
            "min_pixels": args.min_pixels,
            "max_pixels": args.max_pixels,
        },
    )
    sampling_params = SamplingParams(
        temperature=0.0,
        max_tokens=args.max_tokens,
    )

    outputs = existing_outputs
    total = len(records)
    start_completed = len(seen_ids)
    print(
        f"Starting vLLM Proposed Inference: total={total}, "
        f"finished={start_completed}, remaining={len(records_to_run)}, batch_size={args.batch_size}"
    )
    start_time = time.perf_counter()
    progress = tqdm(total=total, initial=start_completed, unit="sample", desc="Ours vLLM", dynamic_ncols=True)
    for batch_idx, (_, chunk) in enumerate(iter_chunks(records_to_run, args.batch_size), start=1):
        batch_start = time.perf_counter()
        yolo_start = time.perf_counter()
        requests, meta = make_requests(chunk, args.image_dir, yolo_model, args.yolo_batch_size)
        yolo_elapsed = time.perf_counter() - yolo_start
        vllm_start = time.perf_counter()
        responses = llm.generate(requests, sampling_params=sampling_params, use_tqdm=args.vllm_progress)
        vllm_elapsed = time.perf_counter() - vllm_start
        batch_outputs = []
        for response, item in zip(responses, meta):
            full_text = response.outputs[0].text
            extracted_ans = extract_answer(full_text, item["task_type"])
            batch_outputs.append({
                "id": item["id"],
                "task_type": item["task_type"],
                "model_full_output": full_text,
                "extracted_answer": extracted_ans,
                "ground_truth": item["answer"],
                "is_correct": str(extracted_ans).strip().lower() == str(item["answer"]).strip().lower()
                if item["task_type"] == "mc" else None,
            })
        append_jsonl(resume_path, batch_outputs)
        outputs.extend(batch_outputs)
        progress.update(len(chunk))
        elapsed = time.perf_counter() - start_time
        completed = len(outputs)
        newly_completed = completed - start_completed
        avg = elapsed / newly_completed if newly_completed else 0
        remaining = avg * (total - completed)
        progress.set_postfix({
            "batch": batch_idx,
            "batch_s": f"{time.perf_counter() - batch_start:.1f}",
            "yolo_s": f"{yolo_elapsed:.1f}",
            "vllm_s": f"{vllm_elapsed:.1f}",
            "avg_s": f"{avg:.2f}",
            "eta": format_duration(remaining),
        })
    progress.close()

    out_path = os.path.join(args.out_dir, f"proposed_vllm_results_{time.strftime('%y%m%d_%H%M')}.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(outputs, f, indent=4, ensure_ascii=False)
    elapsed = time.perf_counter() - start_time
    print(
        f"Proposed vLLM finished: {len(outputs)}/{total} samples, "
        f"elapsed={format_duration(elapsed)}, avg={elapsed / max(len(outputs) - start_completed, 1):.2f}s/new_sample"
    )
    print(f"Results saved to {out_path}")
    print(f"Resume checkpoint kept at {resume_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", type=str, default=DEFAULT_MODEL_PATH)
    parser.add_argument("--dataset-file", type=str, default=DEFAULT_DATASET_FILE)
    parser.add_argument("--image-dir", type=str, default=DEFAULT_IMAGE_DIR)
    parser.add_argument("--yolo-path", type=str, default=DEFAULT_YOLO_PATH)
    parser.add_argument("--out-dir", type=str, default=DEFAULT_OUT_DIR)
    parser.add_argument("--batch-size", type=int, default=64)
    parser.add_argument("--yolo-batch-size", type=int, default=64)
    parser.add_argument("--max-tokens", type=int, default=512)
    parser.add_argument("--max-model-len", type=int, default=4096)
    parser.add_argument("--max-num-seqs", type=int, default=64)
    parser.add_argument("--gpu-memory-utilization", type=float, default=0.75)
    parser.add_argument("--min-pixels", type=int, default=28 * 28)
    parser.add_argument("--max-pixels", type=int, default=1280 * 28 * 28)
    parser.add_argument("--vllm-progress", action="store_true", help="Show vLLM's per-batch internal progress bars.")
    parser.add_argument("--resume-file", type=str, default=None, help="JSONL checkpoint file. Defaults to OUT_DIR/ours_vllm_resume.jsonl.")
    main(parser.parse_args())
